#!/usr/bin/python

import json
import urllib2
import requests

def clusterstatus():
  clusterstatus = urllib2.urlopen('http://localhost:8983/solr/admin/collections?action=clusterstatus&wt=json')
  data = json.load(clusterstatus)
  return data

def getnodes(data):
  nodes = sorted(data["cluster"]["live_nodes"])
  return nodes

data = clusterstatus()
nodes = getnodes(data)

for collection,meta0 in data["cluster"]["collections"].iteritems():
  print "start "+collection
  requests.get("http://localhost:8983/solr/admin/collections?action=REBALANCELEADERS&&collection="+collection+"&maxAtOnce=5")
  print collection+" done"
